// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: s3.proto

#include "s3.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR S3Req::S3Req(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.bucket_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.blob_)*/nullptr
  , /*decltype(_impl_.offset_)*/uint64_t{0u}
  , /*decltype(_impl_.count_)*/uint64_t{0u}
  , /*decltype(_impl_.cache_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S3ReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S3ReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S3ReqDefaultTypeInternal() {}
  union {
    S3Req _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S3ReqDefaultTypeInternal _S3Req_default_instance_;
PROTOBUF_CONSTEXPR S3Rep::S3Rep(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.blob_)*/nullptr
  , /*decltype(_impl_.ok_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S3RepDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S3RepDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S3RepDefaultTypeInternal() {}
  union {
    S3Rep _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S3RepDefaultTypeInternal _S3Rep_default_instance_;
static ::_pb::Metadata file_level_metadata_s3_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_s3_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_s3_2eproto = nullptr;

const uint32_t TableStruct_s3_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::S3Req, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::S3Req, _impl_.bucket_),
  PROTOBUF_FIELD_OFFSET(::S3Req, _impl_.key_),
  PROTOBUF_FIELD_OFFSET(::S3Req, _impl_.cache_),
  PROTOBUF_FIELD_OFFSET(::S3Req, _impl_.blob_),
  PROTOBUF_FIELD_OFFSET(::S3Req, _impl_.offset_),
  PROTOBUF_FIELD_OFFSET(::S3Req, _impl_.count_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::S3Rep, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::S3Rep, _impl_.ok_),
  PROTOBUF_FIELD_OFFSET(::S3Rep, _impl_.blob_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::S3Req)},
  { 12, -1, -1, sizeof(::S3Rep)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_S3Req_default_instance_._instance,
  &::_S3Rep_default_instance_._instance,
};

const char descriptor_table_protodef_s3_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\010s3.proto\032\023rpc/proto/rpc.proto\"g\n\005S3Req"
  "\022\016\n\006bucket\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022\r\n\005cache\030\003"
  " \001(\010\022\023\n\004blob\030\004 \001(\0132\005.Blob\022\016\n\006offset\030\005 \001("
  "\004\022\r\n\005count\030\006 \001(\004\"(\n\005S3Rep\022\n\n\002oK\030\001 \001(\010\022\023\n"
  "\004blob\030\002 \001(\0132\005.BlobB\030Z\026sigmaos/proxy/s3/p"
  "rotob\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_s3_2eproto_deps[1] = {
  &::descriptor_table_rpc_2fproto_2frpc_2eproto,
};
static ::_pbi::once_flag descriptor_table_s3_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_s3_2eproto = {
    false, false, 212, descriptor_table_protodef_s3_2eproto,
    "s3.proto",
    &descriptor_table_s3_2eproto_once, descriptor_table_s3_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_s3_2eproto::offsets,
    file_level_metadata_s3_2eproto, file_level_enum_descriptors_s3_2eproto,
    file_level_service_descriptors_s3_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_s3_2eproto_getter() {
  return &descriptor_table_s3_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_s3_2eproto(&descriptor_table_s3_2eproto);

// ===================================================================

class S3Req::_Internal {
 public:
  static const ::Blob& blob(const S3Req* msg);
};

const ::Blob&
S3Req::_Internal::blob(const S3Req* msg) {
  return *msg->_impl_.blob_;
}
void S3Req::clear_blob() {
  if (GetArenaForAllocation() == nullptr && _impl_.blob_ != nullptr) {
    delete _impl_.blob_;
  }
  _impl_.blob_ = nullptr;
}
S3Req::S3Req(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:S3Req)
}
S3Req::S3Req(const S3Req& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S3Req* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.bucket_){}
    , decltype(_impl_.key_){}
    , decltype(_impl_.blob_){nullptr}
    , decltype(_impl_.offset_){}
    , decltype(_impl_.count_){}
    , decltype(_impl_.cache_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.bucket_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bucket_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_bucket().empty()) {
    _this->_impl_.bucket_.Set(from._internal_bucket(), 
      _this->GetArenaForAllocation());
  }
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_key().empty()) {
    _this->_impl_.key_.Set(from._internal_key(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_blob()) {
    _this->_impl_.blob_ = new ::Blob(*from._impl_.blob_);
  }
  ::memcpy(&_impl_.offset_, &from._impl_.offset_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.cache_) -
    reinterpret_cast<char*>(&_impl_.offset_)) + sizeof(_impl_.cache_));
  // @@protoc_insertion_point(copy_constructor:S3Req)
}

inline void S3Req::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.bucket_){}
    , decltype(_impl_.key_){}
    , decltype(_impl_.blob_){nullptr}
    , decltype(_impl_.offset_){uint64_t{0u}}
    , decltype(_impl_.count_){uint64_t{0u}}
    , decltype(_impl_.cache_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.bucket_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bucket_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

S3Req::~S3Req() {
  // @@protoc_insertion_point(destructor:S3Req)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S3Req::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.bucket_.Destroy();
  _impl_.key_.Destroy();
  if (this != internal_default_instance()) delete _impl_.blob_;
}

void S3Req::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S3Req::Clear() {
// @@protoc_insertion_point(message_clear_start:S3Req)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.bucket_.ClearToEmpty();
  _impl_.key_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.blob_ != nullptr) {
    delete _impl_.blob_;
  }
  _impl_.blob_ = nullptr;
  ::memset(&_impl_.offset_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.cache_) -
      reinterpret_cast<char*>(&_impl_.offset_)) + sizeof(_impl_.cache_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S3Req::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string bucket = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_bucket();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "S3Req.bucket"));
        } else
          goto handle_unusual;
        continue;
      // string key = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "S3Req.key"));
        } else
          goto handle_unusual;
        continue;
      // bool cache = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.cache_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Blob blob = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_blob(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 offset = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 count = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S3Req::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:S3Req)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string bucket = 1;
  if (!this->_internal_bucket().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_bucket().data(), static_cast<int>(this->_internal_bucket().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "S3Req.bucket");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_bucket(), target);
  }

  // string key = 2;
  if (!this->_internal_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_key().data(), static_cast<int>(this->_internal_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "S3Req.key");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_key(), target);
  }

  // bool cache = 3;
  if (this->_internal_cache() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_cache(), target);
  }

  // .Blob blob = 4;
  if (this->_internal_has_blob()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::blob(this),
        _Internal::blob(this).GetCachedSize(), target, stream);
  }

  // uint64 offset = 5;
  if (this->_internal_offset() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_offset(), target);
  }

  // uint64 count = 6;
  if (this->_internal_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(6, this->_internal_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:S3Req)
  return target;
}

size_t S3Req::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:S3Req)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string bucket = 1;
  if (!this->_internal_bucket().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_bucket());
  }

  // string key = 2;
  if (!this->_internal_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_key());
  }

  // .Blob blob = 4;
  if (this->_internal_has_blob()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.blob_);
  }

  // uint64 offset = 5;
  if (this->_internal_offset() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_offset());
  }

  // uint64 count = 6;
  if (this->_internal_count() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_count());
  }

  // bool cache = 3;
  if (this->_internal_cache() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S3Req::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S3Req::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S3Req::GetClassData() const { return &_class_data_; }


void S3Req::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S3Req*>(&to_msg);
  auto& from = static_cast<const S3Req&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:S3Req)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_bucket().empty()) {
    _this->_internal_set_bucket(from._internal_bucket());
  }
  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  if (from._internal_has_blob()) {
    _this->_internal_mutable_blob()->::Blob::MergeFrom(
        from._internal_blob());
  }
  if (from._internal_offset() != 0) {
    _this->_internal_set_offset(from._internal_offset());
  }
  if (from._internal_count() != 0) {
    _this->_internal_set_count(from._internal_count());
  }
  if (from._internal_cache() != 0) {
    _this->_internal_set_cache(from._internal_cache());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S3Req::CopyFrom(const S3Req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:S3Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S3Req::IsInitialized() const {
  return true;
}

void S3Req::InternalSwap(S3Req* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.bucket_, lhs_arena,
      &other->_impl_.bucket_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.key_, lhs_arena,
      &other->_impl_.key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S3Req, _impl_.cache_)
      + sizeof(S3Req::_impl_.cache_)
      - PROTOBUF_FIELD_OFFSET(S3Req, _impl_.blob_)>(
          reinterpret_cast<char*>(&_impl_.blob_),
          reinterpret_cast<char*>(&other->_impl_.blob_));
}

::PROTOBUF_NAMESPACE_ID::Metadata S3Req::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_s3_2eproto_getter, &descriptor_table_s3_2eproto_once,
      file_level_metadata_s3_2eproto[0]);
}

// ===================================================================

class S3Rep::_Internal {
 public:
  static const ::Blob& blob(const S3Rep* msg);
};

const ::Blob&
S3Rep::_Internal::blob(const S3Rep* msg) {
  return *msg->_impl_.blob_;
}
void S3Rep::clear_blob() {
  if (GetArenaForAllocation() == nullptr && _impl_.blob_ != nullptr) {
    delete _impl_.blob_;
  }
  _impl_.blob_ = nullptr;
}
S3Rep::S3Rep(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:S3Rep)
}
S3Rep::S3Rep(const S3Rep& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S3Rep* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.blob_){nullptr}
    , decltype(_impl_.ok_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_blob()) {
    _this->_impl_.blob_ = new ::Blob(*from._impl_.blob_);
  }
  _this->_impl_.ok_ = from._impl_.ok_;
  // @@protoc_insertion_point(copy_constructor:S3Rep)
}

inline void S3Rep::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.blob_){nullptr}
    , decltype(_impl_.ok_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

S3Rep::~S3Rep() {
  // @@protoc_insertion_point(destructor:S3Rep)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S3Rep::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.blob_;
}

void S3Rep::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S3Rep::Clear() {
// @@protoc_insertion_point(message_clear_start:S3Rep)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.blob_ != nullptr) {
    delete _impl_.blob_;
  }
  _impl_.blob_ = nullptr;
  _impl_.ok_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S3Rep::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool oK = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.ok_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Blob blob = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_blob(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S3Rep::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:S3Rep)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool oK = 1;
  if (this->_internal_ok() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_ok(), target);
  }

  // .Blob blob = 2;
  if (this->_internal_has_blob()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::blob(this),
        _Internal::blob(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:S3Rep)
  return target;
}

size_t S3Rep::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:S3Rep)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Blob blob = 2;
  if (this->_internal_has_blob()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.blob_);
  }

  // bool oK = 1;
  if (this->_internal_ok() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S3Rep::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S3Rep::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S3Rep::GetClassData() const { return &_class_data_; }


void S3Rep::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S3Rep*>(&to_msg);
  auto& from = static_cast<const S3Rep&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:S3Rep)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_blob()) {
    _this->_internal_mutable_blob()->::Blob::MergeFrom(
        from._internal_blob());
  }
  if (from._internal_ok() != 0) {
    _this->_internal_set_ok(from._internal_ok());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S3Rep::CopyFrom(const S3Rep& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:S3Rep)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S3Rep::IsInitialized() const {
  return true;
}

void S3Rep::InternalSwap(S3Rep* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S3Rep, _impl_.ok_)
      + sizeof(S3Rep::_impl_.ok_)
      - PROTOBUF_FIELD_OFFSET(S3Rep, _impl_.blob_)>(
          reinterpret_cast<char*>(&_impl_.blob_),
          reinterpret_cast<char*>(&other->_impl_.blob_));
}

::PROTOBUF_NAMESPACE_ID::Metadata S3Rep::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_s3_2eproto_getter, &descriptor_table_s3_2eproto_once,
      file_level_metadata_s3_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::S3Req*
Arena::CreateMaybeMessage< ::S3Req >(Arena* arena) {
  return Arena::CreateMessageInternal< ::S3Req >(arena);
}
template<> PROTOBUF_NOINLINE ::S3Rep*
Arena::CreateMaybeMessage< ::S3Rep >(Arena* arena) {
  return Arena::CreateMessageInternal< ::S3Rep >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
