// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: s3.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_s3_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_s3_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "rpc/proto/rpc.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_s3_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_s3_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_s3_2eproto;
class S3Rep;
struct S3RepDefaultTypeInternal;
extern S3RepDefaultTypeInternal _S3Rep_default_instance_;
class S3Req;
struct S3ReqDefaultTypeInternal;
extern S3ReqDefaultTypeInternal _S3Req_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::S3Rep* Arena::CreateMaybeMessage<::S3Rep>(Arena*);
template<> ::S3Req* Arena::CreateMaybeMessage<::S3Req>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class S3Req final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:S3Req) */ {
 public:
  inline S3Req() : S3Req(nullptr) {}
  ~S3Req() override;
  explicit PROTOBUF_CONSTEXPR S3Req(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S3Req(const S3Req& from);
  S3Req(S3Req&& from) noexcept
    : S3Req() {
    *this = ::std::move(from);
  }

  inline S3Req& operator=(const S3Req& from) {
    CopyFrom(from);
    return *this;
  }
  inline S3Req& operator=(S3Req&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S3Req& default_instance() {
    return *internal_default_instance();
  }
  static inline const S3Req* internal_default_instance() {
    return reinterpret_cast<const S3Req*>(
               &_S3Req_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(S3Req& a, S3Req& b) {
    a.Swap(&b);
  }
  inline void Swap(S3Req* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S3Req* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S3Req* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S3Req>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S3Req& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S3Req& from) {
    S3Req::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S3Req* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "S3Req";
  }
  protected:
  explicit S3Req(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBucketFieldNumber = 1,
    kKeyFieldNumber = 2,
    kBlobFieldNumber = 4,
    kOffsetFieldNumber = 5,
    kCountFieldNumber = 6,
    kCacheFieldNumber = 3,
  };
  // string bucket = 1;
  void clear_bucket();
  const std::string& bucket() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_bucket(ArgT0&& arg0, ArgT... args);
  std::string* mutable_bucket();
  PROTOBUF_NODISCARD std::string* release_bucket();
  void set_allocated_bucket(std::string* bucket);
  private:
  const std::string& _internal_bucket() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bucket(const std::string& value);
  std::string* _internal_mutable_bucket();
  public:

  // string key = 2;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // .Blob blob = 4;
  bool has_blob() const;
  private:
  bool _internal_has_blob() const;
  public:
  void clear_blob();
  const ::Blob& blob() const;
  PROTOBUF_NODISCARD ::Blob* release_blob();
  ::Blob* mutable_blob();
  void set_allocated_blob(::Blob* blob);
  private:
  const ::Blob& _internal_blob() const;
  ::Blob* _internal_mutable_blob();
  public:
  void unsafe_arena_set_allocated_blob(
      ::Blob* blob);
  ::Blob* unsafe_arena_release_blob();

  // uint64 offset = 5;
  void clear_offset();
  uint64_t offset() const;
  void set_offset(uint64_t value);
  private:
  uint64_t _internal_offset() const;
  void _internal_set_offset(uint64_t value);
  public:

  // uint64 count = 6;
  void clear_count();
  uint64_t count() const;
  void set_count(uint64_t value);
  private:
  uint64_t _internal_count() const;
  void _internal_set_count(uint64_t value);
  public:

  // bool cache = 3;
  void clear_cache();
  bool cache() const;
  void set_cache(bool value);
  private:
  bool _internal_cache() const;
  void _internal_set_cache(bool value);
  public:

  // @@protoc_insertion_point(class_scope:S3Req)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bucket_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    ::Blob* blob_;
    uint64_t offset_;
    uint64_t count_;
    bool cache_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_s3_2eproto;
};
// -------------------------------------------------------------------

class S3Rep final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:S3Rep) */ {
 public:
  inline S3Rep() : S3Rep(nullptr) {}
  ~S3Rep() override;
  explicit PROTOBUF_CONSTEXPR S3Rep(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S3Rep(const S3Rep& from);
  S3Rep(S3Rep&& from) noexcept
    : S3Rep() {
    *this = ::std::move(from);
  }

  inline S3Rep& operator=(const S3Rep& from) {
    CopyFrom(from);
    return *this;
  }
  inline S3Rep& operator=(S3Rep&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S3Rep& default_instance() {
    return *internal_default_instance();
  }
  static inline const S3Rep* internal_default_instance() {
    return reinterpret_cast<const S3Rep*>(
               &_S3Rep_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S3Rep& a, S3Rep& b) {
    a.Swap(&b);
  }
  inline void Swap(S3Rep* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S3Rep* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S3Rep* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S3Rep>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S3Rep& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S3Rep& from) {
    S3Rep::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S3Rep* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "S3Rep";
  }
  protected:
  explicit S3Rep(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBlobFieldNumber = 2,
    kOKFieldNumber = 1,
  };
  // .Blob blob = 2;
  bool has_blob() const;
  private:
  bool _internal_has_blob() const;
  public:
  void clear_blob();
  const ::Blob& blob() const;
  PROTOBUF_NODISCARD ::Blob* release_blob();
  ::Blob* mutable_blob();
  void set_allocated_blob(::Blob* blob);
  private:
  const ::Blob& _internal_blob() const;
  ::Blob* _internal_mutable_blob();
  public:
  void unsafe_arena_set_allocated_blob(
      ::Blob* blob);
  ::Blob* unsafe_arena_release_blob();

  // bool oK = 1;
  void clear_ok();
  bool ok() const;
  void set_ok(bool value);
  private:
  bool _internal_ok() const;
  void _internal_set_ok(bool value);
  public:

  // @@protoc_insertion_point(class_scope:S3Rep)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Blob* blob_;
    bool ok_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_s3_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// S3Req

// string bucket = 1;
inline void S3Req::clear_bucket() {
  _impl_.bucket_.ClearToEmpty();
}
inline const std::string& S3Req::bucket() const {
  // @@protoc_insertion_point(field_get:S3Req.bucket)
  return _internal_bucket();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void S3Req::set_bucket(ArgT0&& arg0, ArgT... args) {
 
 _impl_.bucket_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:S3Req.bucket)
}
inline std::string* S3Req::mutable_bucket() {
  std::string* _s = _internal_mutable_bucket();
  // @@protoc_insertion_point(field_mutable:S3Req.bucket)
  return _s;
}
inline const std::string& S3Req::_internal_bucket() const {
  return _impl_.bucket_.Get();
}
inline void S3Req::_internal_set_bucket(const std::string& value) {
  
  _impl_.bucket_.Set(value, GetArenaForAllocation());
}
inline std::string* S3Req::_internal_mutable_bucket() {
  
  return _impl_.bucket_.Mutable(GetArenaForAllocation());
}
inline std::string* S3Req::release_bucket() {
  // @@protoc_insertion_point(field_release:S3Req.bucket)
  return _impl_.bucket_.Release();
}
inline void S3Req::set_allocated_bucket(std::string* bucket) {
  if (bucket != nullptr) {
    
  } else {
    
  }
  _impl_.bucket_.SetAllocated(bucket, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.bucket_.IsDefault()) {
    _impl_.bucket_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:S3Req.bucket)
}

// string key = 2;
inline void S3Req::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& S3Req::key() const {
  // @@protoc_insertion_point(field_get:S3Req.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void S3Req::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:S3Req.key)
}
inline std::string* S3Req::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:S3Req.key)
  return _s;
}
inline const std::string& S3Req::_internal_key() const {
  return _impl_.key_.Get();
}
inline void S3Req::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* S3Req::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* S3Req::release_key() {
  // @@protoc_insertion_point(field_release:S3Req.key)
  return _impl_.key_.Release();
}
inline void S3Req::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:S3Req.key)
}

// bool cache = 3;
inline void S3Req::clear_cache() {
  _impl_.cache_ = false;
}
inline bool S3Req::_internal_cache() const {
  return _impl_.cache_;
}
inline bool S3Req::cache() const {
  // @@protoc_insertion_point(field_get:S3Req.cache)
  return _internal_cache();
}
inline void S3Req::_internal_set_cache(bool value) {
  
  _impl_.cache_ = value;
}
inline void S3Req::set_cache(bool value) {
  _internal_set_cache(value);
  // @@protoc_insertion_point(field_set:S3Req.cache)
}

// .Blob blob = 4;
inline bool S3Req::_internal_has_blob() const {
  return this != internal_default_instance() && _impl_.blob_ != nullptr;
}
inline bool S3Req::has_blob() const {
  return _internal_has_blob();
}
inline const ::Blob& S3Req::_internal_blob() const {
  const ::Blob* p = _impl_.blob_;
  return p != nullptr ? *p : reinterpret_cast<const ::Blob&>(
      ::_Blob_default_instance_);
}
inline const ::Blob& S3Req::blob() const {
  // @@protoc_insertion_point(field_get:S3Req.blob)
  return _internal_blob();
}
inline void S3Req::unsafe_arena_set_allocated_blob(
    ::Blob* blob) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.blob_);
  }
  _impl_.blob_ = blob;
  if (blob) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:S3Req.blob)
}
inline ::Blob* S3Req::release_blob() {
  
  ::Blob* temp = _impl_.blob_;
  _impl_.blob_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Blob* S3Req::unsafe_arena_release_blob() {
  // @@protoc_insertion_point(field_release:S3Req.blob)
  
  ::Blob* temp = _impl_.blob_;
  _impl_.blob_ = nullptr;
  return temp;
}
inline ::Blob* S3Req::_internal_mutable_blob() {
  
  if (_impl_.blob_ == nullptr) {
    auto* p = CreateMaybeMessage<::Blob>(GetArenaForAllocation());
    _impl_.blob_ = p;
  }
  return _impl_.blob_;
}
inline ::Blob* S3Req::mutable_blob() {
  ::Blob* _msg = _internal_mutable_blob();
  // @@protoc_insertion_point(field_mutable:S3Req.blob)
  return _msg;
}
inline void S3Req::set_allocated_blob(::Blob* blob) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.blob_);
  }
  if (blob) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(blob));
    if (message_arena != submessage_arena) {
      blob = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, blob, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.blob_ = blob;
  // @@protoc_insertion_point(field_set_allocated:S3Req.blob)
}

// uint64 offset = 5;
inline void S3Req::clear_offset() {
  _impl_.offset_ = uint64_t{0u};
}
inline uint64_t S3Req::_internal_offset() const {
  return _impl_.offset_;
}
inline uint64_t S3Req::offset() const {
  // @@protoc_insertion_point(field_get:S3Req.offset)
  return _internal_offset();
}
inline void S3Req::_internal_set_offset(uint64_t value) {
  
  _impl_.offset_ = value;
}
inline void S3Req::set_offset(uint64_t value) {
  _internal_set_offset(value);
  // @@protoc_insertion_point(field_set:S3Req.offset)
}

// uint64 count = 6;
inline void S3Req::clear_count() {
  _impl_.count_ = uint64_t{0u};
}
inline uint64_t S3Req::_internal_count() const {
  return _impl_.count_;
}
inline uint64_t S3Req::count() const {
  // @@protoc_insertion_point(field_get:S3Req.count)
  return _internal_count();
}
inline void S3Req::_internal_set_count(uint64_t value) {
  
  _impl_.count_ = value;
}
inline void S3Req::set_count(uint64_t value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:S3Req.count)
}

// -------------------------------------------------------------------

// S3Rep

// bool oK = 1;
inline void S3Rep::clear_ok() {
  _impl_.ok_ = false;
}
inline bool S3Rep::_internal_ok() const {
  return _impl_.ok_;
}
inline bool S3Rep::ok() const {
  // @@protoc_insertion_point(field_get:S3Rep.oK)
  return _internal_ok();
}
inline void S3Rep::_internal_set_ok(bool value) {
  
  _impl_.ok_ = value;
}
inline void S3Rep::set_ok(bool value) {
  _internal_set_ok(value);
  // @@protoc_insertion_point(field_set:S3Rep.oK)
}

// .Blob blob = 2;
inline bool S3Rep::_internal_has_blob() const {
  return this != internal_default_instance() && _impl_.blob_ != nullptr;
}
inline bool S3Rep::has_blob() const {
  return _internal_has_blob();
}
inline const ::Blob& S3Rep::_internal_blob() const {
  const ::Blob* p = _impl_.blob_;
  return p != nullptr ? *p : reinterpret_cast<const ::Blob&>(
      ::_Blob_default_instance_);
}
inline const ::Blob& S3Rep::blob() const {
  // @@protoc_insertion_point(field_get:S3Rep.blob)
  return _internal_blob();
}
inline void S3Rep::unsafe_arena_set_allocated_blob(
    ::Blob* blob) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.blob_);
  }
  _impl_.blob_ = blob;
  if (blob) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:S3Rep.blob)
}
inline ::Blob* S3Rep::release_blob() {
  
  ::Blob* temp = _impl_.blob_;
  _impl_.blob_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Blob* S3Rep::unsafe_arena_release_blob() {
  // @@protoc_insertion_point(field_release:S3Rep.blob)
  
  ::Blob* temp = _impl_.blob_;
  _impl_.blob_ = nullptr;
  return temp;
}
inline ::Blob* S3Rep::_internal_mutable_blob() {
  
  if (_impl_.blob_ == nullptr) {
    auto* p = CreateMaybeMessage<::Blob>(GetArenaForAllocation());
    _impl_.blob_ = p;
  }
  return _impl_.blob_;
}
inline ::Blob* S3Rep::mutable_blob() {
  ::Blob* _msg = _internal_mutable_blob();
  // @@protoc_insertion_point(field_mutable:S3Rep.blob)
  return _msg;
}
inline void S3Rep::set_allocated_blob(::Blob* blob) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.blob_);
  }
  if (blob) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(blob));
    if (message_arena != submessage_arena) {
      blob = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, blob, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.blob_ = blob;
  // @@protoc_insertion_point(field_set_allocated:S3Rep.blob)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_s3_2eproto
