package crash

type Tselector string

const (
	NAMED_PARTITION     = "NAMED_PARTITION"
	NAMED_CRASH         = "NAMED_CRASH"
	NAMED_CRASHFILE     = "NAMED_CRASHFILE"
	NAMED_NETFAIL       = "NAMED_NETFAIL"
	NAMED_NETDISCONNECT = "NAMED_NETDISCONNECT"

	LCSCHED_CRASH = "LCSCHED_CRASH"
	BESCHED_CRASH = "BESCHED_CRASH"
	PROCD_CRASH   = "PROCD_CRASH"
	MSCHED_CRASH  = "MSCHED_CRASH"

	SPAWNER_CRASH     = "SPAWNER_CRASH"
	SPAWNER_PARTITION = "SPAWNER_PARTITION"

	CRASH_CRASH     = "CRASH_CRASH"
	CRASH_PARTITION = "CRASH_PARTITION"

	UX_CRASH = "UX_CRASH"

	MRCOORD_CRASH      = "MRCOORD_CRASH"
	MRCOORD_PARTITION  = "MRCOORD_PARTITION"
	MRMAP_CRASH        = "MRMAP_CRASH"
	MRMAP_PARTITION    = "MRMAP_PARTITION"
	MRREDUCE_CRASH     = "MRREDUCE_CRASH"
	MRREDUCE_PARTITION = "MRREDUCE_PARTITION"

	KVBALANCER_CRASH     = "KVBALANCER_CRASH"
	KVBALANCER_PARTITION = "KVBALANCER_PARTITION"
	KVMOVER_EVENT        = "KVMOVER_EVENT"

	KVD_CRASH     = "KVD_CRASH"
	KVD_PARTITION = "KVD_PARTITION"
	KVD_NETFAIL   = "KVD_NETFAIL"

	IMGRESIZE_CRASH = "IMGRESIZE_CRASH"
)
