// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.0
// source: apps/cache/proto/dump.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	proto "sigmaos/rpc/proto"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiShardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shards []uint32 `protobuf:"varint,1,rep,packed,name=shards,proto3" json:"shards,omitempty"`
}

func (x *MultiShardReq) Reset() {
	*x = MultiShardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_cache_proto_dump_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiShardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiShardReq) ProtoMessage() {}

func (x *MultiShardReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_cache_proto_dump_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiShardReq.ProtoReflect.Descriptor instead.
func (*MultiShardReq) Descriptor() ([]byte, []int) {
	return file_apps_cache_proto_dump_proto_rawDescGZIP(), []int{0}
}

func (x *MultiShardReq) GetShards() []uint32 {
	if x != nil {
		return x.Shards
	}
	return nil
}

type MultiShardRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string    `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Lens []uint32    `protobuf:"varint,2,rep,packed,name=lens,proto3" json:"lens,omitempty"`
	Blob *proto.Blob `protobuf:"bytes,3,opt,name=blob,proto3" json:"blob,omitempty"`
}

func (x *MultiShardRep) Reset() {
	*x = MultiShardRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_cache_proto_dump_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiShardRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiShardRep) ProtoMessage() {}

func (x *MultiShardRep) ProtoReflect() protoreflect.Message {
	mi := &file_apps_cache_proto_dump_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiShardRep.ProtoReflect.Descriptor instead.
func (*MultiShardRep) Descriptor() ([]byte, []int) {
	return file_apps_cache_proto_dump_proto_rawDescGZIP(), []int{1}
}

func (x *MultiShardRep) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *MultiShardRep) GetLens() []uint32 {
	if x != nil {
		return x.Lens
	}
	return nil
}

func (x *MultiShardRep) GetBlob() *proto.Blob {
	if x != nil {
		return x.Blob
	}
	return nil
}

var File_apps_cache_proto_dump_proto protoreflect.FileDescriptor

var file_apps_cache_proto_dump_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x64, 0x75, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0d, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x68, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x22, 0x52, 0x0a, 0x0d, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04,
	0x6c, 0x65, 0x6e, 0x73, 0x12, 0x19, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x42,
	0x1a, 0x5a, 0x18, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_apps_cache_proto_dump_proto_rawDescOnce sync.Once
	file_apps_cache_proto_dump_proto_rawDescData = file_apps_cache_proto_dump_proto_rawDesc
)

func file_apps_cache_proto_dump_proto_rawDescGZIP() []byte {
	file_apps_cache_proto_dump_proto_rawDescOnce.Do(func() {
		file_apps_cache_proto_dump_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_cache_proto_dump_proto_rawDescData)
	})
	return file_apps_cache_proto_dump_proto_rawDescData
}

var file_apps_cache_proto_dump_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apps_cache_proto_dump_proto_goTypes = []interface{}{
	(*MultiShardReq)(nil), // 0: MultiShardReq
	(*MultiShardRep)(nil), // 1: MultiShardRep
	(*proto.Blob)(nil),    // 2: Blob
}
var file_apps_cache_proto_dump_proto_depIdxs = []int32{
	2, // 0: MultiShardRep.blob:type_name -> Blob
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_cache_proto_dump_proto_init() }
func file_apps_cache_proto_dump_proto_init() {
	if File_apps_cache_proto_dump_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_cache_proto_dump_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiShardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_cache_proto_dump_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiShardRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_cache_proto_dump_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_cache_proto_dump_proto_goTypes,
		DependencyIndexes: file_apps_cache_proto_dump_proto_depIdxs,
		MessageInfos:      file_apps_cache_proto_dump_proto_msgTypes,
	}.Build()
	File_apps_cache_proto_dump_proto = out.File
	file_apps_cache_proto_dump_proto_rawDesc = nil
	file_apps_cache_proto_dump_proto_goTypes = nil
	file_apps_cache_proto_dump_proto_depIdxs = nil
}
