// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.0
// source: proxy/s3/proto/s3.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	proto "sigmaos/rpc/proto"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_s3_proto_s3_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_s3_proto_s3_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_proxy_s3_proto_s3_proto_rawDescGZIP(), []int{0}
}

func (x *GetReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK   bool        `protobuf:"varint,1,opt,name=oK,proto3" json:"oK,omitempty"`
	Blob *proto.Blob `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
}

func (x *GetRep) Reset() {
	*x = GetRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_s3_proto_s3_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRep) ProtoMessage() {}

func (x *GetRep) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_s3_proto_s3_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRep.ProtoReflect.Descriptor instead.
func (*GetRep) Descriptor() ([]byte, []int) {
	return file_proxy_s3_proto_s3_proto_rawDescGZIP(), []int{1}
}

func (x *GetRep) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

func (x *GetRep) GetBlob() *proto.Blob {
	if x != nil {
		return x.Blob
	}
	return nil
}

var File_proxy_s3_proto_s3_proto protoreflect.FileDescriptor

var file_proxy_s3_proto_s3_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x73, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x33, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x72, 0x70, 0x63, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x33, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x4b, 0x12, 0x19, 0x0a, 0x04,
	0x62, 0x6c, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x42, 0x6c, 0x6f,
	0x62, 0x52, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x42, 0x18, 0x5a, 0x16, 0x73, 0x69, 0x67, 0x6d, 0x61,
	0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x73, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proxy_s3_proto_s3_proto_rawDescOnce sync.Once
	file_proxy_s3_proto_s3_proto_rawDescData = file_proxy_s3_proto_s3_proto_rawDesc
)

func file_proxy_s3_proto_s3_proto_rawDescGZIP() []byte {
	file_proxy_s3_proto_s3_proto_rawDescOnce.Do(func() {
		file_proxy_s3_proto_s3_proto_rawDescData = protoimpl.X.CompressGZIP(file_proxy_s3_proto_s3_proto_rawDescData)
	})
	return file_proxy_s3_proto_s3_proto_rawDescData
}

var file_proxy_s3_proto_s3_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_s3_proto_s3_proto_goTypes = []interface{}{
	(*GetReq)(nil),     // 0: GetReq
	(*GetRep)(nil),     // 1: GetRep
	(*proto.Blob)(nil), // 2: Blob
}
var file_proxy_s3_proto_s3_proto_depIdxs = []int32{
	2, // 0: GetRep.blob:type_name -> Blob
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proxy_s3_proto_s3_proto_init() }
func file_proxy_s3_proto_s3_proto_init() {
	if File_proxy_s3_proto_s3_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proxy_s3_proto_s3_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_s3_proto_s3_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proxy_s3_proto_s3_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_s3_proto_s3_proto_goTypes,
		DependencyIndexes: file_proxy_s3_proto_s3_proto_depIdxs,
		MessageInfos:      file_proxy_s3_proto_s3_proto_msgTypes,
	}.Build()
	File_proxy_s3_proto_s3_proto = out.File
	file_proxy_s3_proto_s3_proto_rawDesc = nil
	file_proxy_s3_proto_s3_proto_goTypes = nil
	file_proxy_s3_proto_s3_proto_depIdxs = nil
}
