[package]
name = "cossim-boot"
version = "0.1.0"
edition = "2021"

[dependencies]
protobuf = "3.7.2"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = "s"
panic = "abort"
strip = "symbols"
