steps:
- checkout: self
  clean: true
  fetchDepth: 5

# Work around a known issue affecting Ubuntu VMs on Pipelines
- script: sudo setfacl -Rb /home/vsts
  displayName: 'Workaround ACL issue'

- script: sudo ./.azure-pipelines/posix-deps-apt.sh $(openssl_version)
  displayName: 'Install dependencies'

- script: ./configure --with-pydebug
  displayName: 'Configure CPython (debug)'

- script: make -j4
  displayName: 'Build CPython'

- script: make pythoninfo
  displayName: 'Display build info'

- script: |
    git fetch origin
    ./python Tools/scripts/patchcheck.py --ci true
  displayName: 'Run patchcheck.py'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))

