// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dump.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_dump_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_dump_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "rpc/proto/rpc.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_dump_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_dump_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_dump_2eproto;
class MultiShardRep;
struct MultiShardRepDefaultTypeInternal;
extern MultiShardRepDefaultTypeInternal _MultiShardRep_default_instance_;
class MultiShardReq;
struct MultiShardReqDefaultTypeInternal;
extern MultiShardReqDefaultTypeInternal _MultiShardReq_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::MultiShardRep* Arena::CreateMaybeMessage<::MultiShardRep>(Arena*);
template<> ::MultiShardReq* Arena::CreateMaybeMessage<::MultiShardReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class MultiShardReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MultiShardReq) */ {
 public:
  inline MultiShardReq() : MultiShardReq(nullptr) {}
  ~MultiShardReq() override;
  explicit PROTOBUF_CONSTEXPR MultiShardReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MultiShardReq(const MultiShardReq& from);
  MultiShardReq(MultiShardReq&& from) noexcept
    : MultiShardReq() {
    *this = ::std::move(from);
  }

  inline MultiShardReq& operator=(const MultiShardReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline MultiShardReq& operator=(MultiShardReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MultiShardReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const MultiShardReq* internal_default_instance() {
    return reinterpret_cast<const MultiShardReq*>(
               &_MultiShardReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MultiShardReq& a, MultiShardReq& b) {
    a.Swap(&b);
  }
  inline void Swap(MultiShardReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MultiShardReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MultiShardReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MultiShardReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MultiShardReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MultiShardReq& from) {
    MultiShardReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MultiShardReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MultiShardReq";
  }
  protected:
  explicit MultiShardReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShardsFieldNumber = 1,
  };
  // repeated uint32 shards = 1;
  int shards_size() const;
  private:
  int _internal_shards_size() const;
  public:
  void clear_shards();
  private:
  uint32_t _internal_shards(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_shards() const;
  void _internal_add_shards(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_shards();
  public:
  uint32_t shards(int index) const;
  void set_shards(int index, uint32_t value);
  void add_shards(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      shards() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_shards();

  // @@protoc_insertion_point(class_scope:MultiShardReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > shards_;
    mutable std::atomic<int> _shards_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dump_2eproto;
};
// -------------------------------------------------------------------

class MultiShardRep final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MultiShardRep) */ {
 public:
  inline MultiShardRep() : MultiShardRep(nullptr) {}
  ~MultiShardRep() override;
  explicit PROTOBUF_CONSTEXPR MultiShardRep(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MultiShardRep(const MultiShardRep& from);
  MultiShardRep(MultiShardRep&& from) noexcept
    : MultiShardRep() {
    *this = ::std::move(from);
  }

  inline MultiShardRep& operator=(const MultiShardRep& from) {
    CopyFrom(from);
    return *this;
  }
  inline MultiShardRep& operator=(MultiShardRep&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MultiShardRep& default_instance() {
    return *internal_default_instance();
  }
  static inline const MultiShardRep* internal_default_instance() {
    return reinterpret_cast<const MultiShardRep*>(
               &_MultiShardRep_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MultiShardRep& a, MultiShardRep& b) {
    a.Swap(&b);
  }
  inline void Swap(MultiShardRep* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MultiShardRep* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MultiShardRep* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MultiShardRep>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MultiShardRep& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MultiShardRep& from) {
    MultiShardRep::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MultiShardRep* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MultiShardRep";
  }
  protected:
  explicit MultiShardRep(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeysFieldNumber = 1,
    kLensFieldNumber = 2,
    kBlobFieldNumber = 3,
  };
  // repeated string keys = 1;
  int keys_size() const;
  private:
  int _internal_keys_size() const;
  public:
  void clear_keys();
  const std::string& keys(int index) const;
  std::string* mutable_keys(int index);
  void set_keys(int index, const std::string& value);
  void set_keys(int index, std::string&& value);
  void set_keys(int index, const char* value);
  void set_keys(int index, const char* value, size_t size);
  std::string* add_keys();
  void add_keys(const std::string& value);
  void add_keys(std::string&& value);
  void add_keys(const char* value);
  void add_keys(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& keys() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_keys();
  private:
  const std::string& _internal_keys(int index) const;
  std::string* _internal_add_keys();
  public:

  // repeated uint32 lens = 2;
  int lens_size() const;
  private:
  int _internal_lens_size() const;
  public:
  void clear_lens();
  private:
  uint32_t _internal_lens(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_lens() const;
  void _internal_add_lens(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_lens();
  public:
  uint32_t lens(int index) const;
  void set_lens(int index, uint32_t value);
  void add_lens(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      lens() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_lens();

  // .Blob blob = 3;
  bool has_blob() const;
  private:
  bool _internal_has_blob() const;
  public:
  void clear_blob();
  const ::Blob& blob() const;
  PROTOBUF_NODISCARD ::Blob* release_blob();
  ::Blob* mutable_blob();
  void set_allocated_blob(::Blob* blob);
  private:
  const ::Blob& _internal_blob() const;
  ::Blob* _internal_mutable_blob();
  public:
  void unsafe_arena_set_allocated_blob(
      ::Blob* blob);
  ::Blob* unsafe_arena_release_blob();

  // @@protoc_insertion_point(class_scope:MultiShardRep)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> keys_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > lens_;
    mutable std::atomic<int> _lens_cached_byte_size_;
    ::Blob* blob_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dump_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MultiShardReq

// repeated uint32 shards = 1;
inline int MultiShardReq::_internal_shards_size() const {
  return _impl_.shards_.size();
}
inline int MultiShardReq::shards_size() const {
  return _internal_shards_size();
}
inline void MultiShardReq::clear_shards() {
  _impl_.shards_.Clear();
}
inline uint32_t MultiShardReq::_internal_shards(int index) const {
  return _impl_.shards_.Get(index);
}
inline uint32_t MultiShardReq::shards(int index) const {
  // @@protoc_insertion_point(field_get:MultiShardReq.shards)
  return _internal_shards(index);
}
inline void MultiShardReq::set_shards(int index, uint32_t value) {
  _impl_.shards_.Set(index, value);
  // @@protoc_insertion_point(field_set:MultiShardReq.shards)
}
inline void MultiShardReq::_internal_add_shards(uint32_t value) {
  _impl_.shards_.Add(value);
}
inline void MultiShardReq::add_shards(uint32_t value) {
  _internal_add_shards(value);
  // @@protoc_insertion_point(field_add:MultiShardReq.shards)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
MultiShardReq::_internal_shards() const {
  return _impl_.shards_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
MultiShardReq::shards() const {
  // @@protoc_insertion_point(field_list:MultiShardReq.shards)
  return _internal_shards();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
MultiShardReq::_internal_mutable_shards() {
  return &_impl_.shards_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
MultiShardReq::mutable_shards() {
  // @@protoc_insertion_point(field_mutable_list:MultiShardReq.shards)
  return _internal_mutable_shards();
}

// -------------------------------------------------------------------

// MultiShardRep

// repeated string keys = 1;
inline int MultiShardRep::_internal_keys_size() const {
  return _impl_.keys_.size();
}
inline int MultiShardRep::keys_size() const {
  return _internal_keys_size();
}
inline void MultiShardRep::clear_keys() {
  _impl_.keys_.Clear();
}
inline std::string* MultiShardRep::add_keys() {
  std::string* _s = _internal_add_keys();
  // @@protoc_insertion_point(field_add_mutable:MultiShardRep.keys)
  return _s;
}
inline const std::string& MultiShardRep::_internal_keys(int index) const {
  return _impl_.keys_.Get(index);
}
inline const std::string& MultiShardRep::keys(int index) const {
  // @@protoc_insertion_point(field_get:MultiShardRep.keys)
  return _internal_keys(index);
}
inline std::string* MultiShardRep::mutable_keys(int index) {
  // @@protoc_insertion_point(field_mutable:MultiShardRep.keys)
  return _impl_.keys_.Mutable(index);
}
inline void MultiShardRep::set_keys(int index, const std::string& value) {
  _impl_.keys_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:MultiShardRep.keys)
}
inline void MultiShardRep::set_keys(int index, std::string&& value) {
  _impl_.keys_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:MultiShardRep.keys)
}
inline void MultiShardRep::set_keys(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.keys_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:MultiShardRep.keys)
}
inline void MultiShardRep::set_keys(int index, const char* value, size_t size) {
  _impl_.keys_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MultiShardRep.keys)
}
inline std::string* MultiShardRep::_internal_add_keys() {
  return _impl_.keys_.Add();
}
inline void MultiShardRep::add_keys(const std::string& value) {
  _impl_.keys_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:MultiShardRep.keys)
}
inline void MultiShardRep::add_keys(std::string&& value) {
  _impl_.keys_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:MultiShardRep.keys)
}
inline void MultiShardRep::add_keys(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.keys_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:MultiShardRep.keys)
}
inline void MultiShardRep::add_keys(const char* value, size_t size) {
  _impl_.keys_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:MultiShardRep.keys)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
MultiShardRep::keys() const {
  // @@protoc_insertion_point(field_list:MultiShardRep.keys)
  return _impl_.keys_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
MultiShardRep::mutable_keys() {
  // @@protoc_insertion_point(field_mutable_list:MultiShardRep.keys)
  return &_impl_.keys_;
}

// repeated uint32 lens = 2;
inline int MultiShardRep::_internal_lens_size() const {
  return _impl_.lens_.size();
}
inline int MultiShardRep::lens_size() const {
  return _internal_lens_size();
}
inline void MultiShardRep::clear_lens() {
  _impl_.lens_.Clear();
}
inline uint32_t MultiShardRep::_internal_lens(int index) const {
  return _impl_.lens_.Get(index);
}
inline uint32_t MultiShardRep::lens(int index) const {
  // @@protoc_insertion_point(field_get:MultiShardRep.lens)
  return _internal_lens(index);
}
inline void MultiShardRep::set_lens(int index, uint32_t value) {
  _impl_.lens_.Set(index, value);
  // @@protoc_insertion_point(field_set:MultiShardRep.lens)
}
inline void MultiShardRep::_internal_add_lens(uint32_t value) {
  _impl_.lens_.Add(value);
}
inline void MultiShardRep::add_lens(uint32_t value) {
  _internal_add_lens(value);
  // @@protoc_insertion_point(field_add:MultiShardRep.lens)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
MultiShardRep::_internal_lens() const {
  return _impl_.lens_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
MultiShardRep::lens() const {
  // @@protoc_insertion_point(field_list:MultiShardRep.lens)
  return _internal_lens();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
MultiShardRep::_internal_mutable_lens() {
  return &_impl_.lens_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
MultiShardRep::mutable_lens() {
  // @@protoc_insertion_point(field_mutable_list:MultiShardRep.lens)
  return _internal_mutable_lens();
}

// .Blob blob = 3;
inline bool MultiShardRep::_internal_has_blob() const {
  return this != internal_default_instance() && _impl_.blob_ != nullptr;
}
inline bool MultiShardRep::has_blob() const {
  return _internal_has_blob();
}
inline const ::Blob& MultiShardRep::_internal_blob() const {
  const ::Blob* p = _impl_.blob_;
  return p != nullptr ? *p : reinterpret_cast<const ::Blob&>(
      ::_Blob_default_instance_);
}
inline const ::Blob& MultiShardRep::blob() const {
  // @@protoc_insertion_point(field_get:MultiShardRep.blob)
  return _internal_blob();
}
inline void MultiShardRep::unsafe_arena_set_allocated_blob(
    ::Blob* blob) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.blob_);
  }
  _impl_.blob_ = blob;
  if (blob) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MultiShardRep.blob)
}
inline ::Blob* MultiShardRep::release_blob() {
  
  ::Blob* temp = _impl_.blob_;
  _impl_.blob_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Blob* MultiShardRep::unsafe_arena_release_blob() {
  // @@protoc_insertion_point(field_release:MultiShardRep.blob)
  
  ::Blob* temp = _impl_.blob_;
  _impl_.blob_ = nullptr;
  return temp;
}
inline ::Blob* MultiShardRep::_internal_mutable_blob() {
  
  if (_impl_.blob_ == nullptr) {
    auto* p = CreateMaybeMessage<::Blob>(GetArenaForAllocation());
    _impl_.blob_ = p;
  }
  return _impl_.blob_;
}
inline ::Blob* MultiShardRep::mutable_blob() {
  ::Blob* _msg = _internal_mutable_blob();
  // @@protoc_insertion_point(field_mutable:MultiShardRep.blob)
  return _msg;
}
inline void MultiShardRep::set_allocated_blob(::Blob* blob) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.blob_);
  }
  if (blob) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(blob));
    if (message_arena != submessage_arena) {
      blob = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, blob, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.blob_ = blob;
  // @@protoc_insertion_point(field_set_allocated:MultiShardRep.blob)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_dump_2eproto
