// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: apps/socialnetwork/proto/text.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComposeUrlsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Extendedurls []string `protobuf:"bytes,1,rep,name=extendedurls,proto3" json:"extendedurls,omitempty"`
}

func (x *ComposeUrlsRequest) Reset() {
	*x = ComposeUrlsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_socialnetwork_proto_text_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComposeUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeUrlsRequest) ProtoMessage() {}

func (x *ComposeUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_socialnetwork_proto_text_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeUrlsRequest.ProtoReflect.Descriptor instead.
func (*ComposeUrlsRequest) Descriptor() ([]byte, []int) {
	return file_apps_socialnetwork_proto_text_proto_rawDescGZIP(), []int{0}
}

func (x *ComposeUrlsRequest) GetExtendedurls() []string {
	if x != nil {
		return x.Extendedurls
	}
	return nil
}

type ComposeUrlsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok        string   `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Shorturls []string `protobuf:"bytes,2,rep,name=shorturls,proto3" json:"shorturls,omitempty"`
}

func (x *ComposeUrlsResponse) Reset() {
	*x = ComposeUrlsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_socialnetwork_proto_text_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComposeUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeUrlsResponse) ProtoMessage() {}

func (x *ComposeUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_socialnetwork_proto_text_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeUrlsResponse.ProtoReflect.Descriptor instead.
func (*ComposeUrlsResponse) Descriptor() ([]byte, []int) {
	return file_apps_socialnetwork_proto_text_proto_rawDescGZIP(), []int{1}
}

func (x *ComposeUrlsResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

func (x *ComposeUrlsResponse) GetShorturls() []string {
	if x != nil {
		return x.Shorturls
	}
	return nil
}

type GetUrlsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shorturls []string `protobuf:"bytes,1,rep,name=shorturls,proto3" json:"shorturls,omitempty"`
}

func (x *GetUrlsRequest) Reset() {
	*x = GetUrlsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_socialnetwork_proto_text_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlsRequest) ProtoMessage() {}

func (x *GetUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_socialnetwork_proto_text_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlsRequest.ProtoReflect.Descriptor instead.
func (*GetUrlsRequest) Descriptor() ([]byte, []int) {
	return file_apps_socialnetwork_proto_text_proto_rawDescGZIP(), []int{2}
}

func (x *GetUrlsRequest) GetShorturls() []string {
	if x != nil {
		return x.Shorturls
	}
	return nil
}

type GetUrlsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok           string   `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Extendedurls []string `protobuf:"bytes,2,rep,name=extendedurls,proto3" json:"extendedurls,omitempty"`
}

func (x *GetUrlsResponse) Reset() {
	*x = GetUrlsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_socialnetwork_proto_text_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlsResponse) ProtoMessage() {}

func (x *GetUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_socialnetwork_proto_text_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlsResponse.ProtoReflect.Descriptor instead.
func (*GetUrlsResponse) Descriptor() ([]byte, []int) {
	return file_apps_socialnetwork_proto_text_proto_rawDescGZIP(), []int{3}
}

func (x *GetUrlsResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

func (x *GetUrlsResponse) GetExtendedurls() []string {
	if x != nil {
		return x.Extendedurls
	}
	return nil
}

type ProcessTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ProcessTextRequest) Reset() {
	*x = ProcessTextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_socialnetwork_proto_text_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTextRequest) ProtoMessage() {}

func (x *ProcessTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_socialnetwork_proto_text_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTextRequest.ProtoReflect.Descriptor instead.
func (*ProcessTextRequest) Descriptor() ([]byte, []int) {
	return file_apps_socialnetwork_proto_text_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ProcessTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok           string   `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Text         string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Usermentions []int64  `protobuf:"varint,3,rep,packed,name=usermentions,proto3" json:"usermentions,omitempty"`
	Urls         []string `protobuf:"bytes,4,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *ProcessTextResponse) Reset() {
	*x = ProcessTextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_socialnetwork_proto_text_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTextResponse) ProtoMessage() {}

func (x *ProcessTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_socialnetwork_proto_text_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTextResponse.ProtoReflect.Descriptor instead.
func (*ProcessTextResponse) Descriptor() ([]byte, []int) {
	return file_apps_socialnetwork_proto_text_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessTextResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

func (x *ProcessTextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ProcessTextResponse) GetUsermentions() []int64 {
	if x != nil {
		return x.Usermentions
	}
	return nil
}

func (x *ProcessTextResponse) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_apps_socialnetwork_proto_text_proto protoreflect.FileDescriptor

var file_apps_socialnetwork_proto_text_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x78, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65,
	0x55, 0x72, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x65,
	0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0c, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x75, 0x72, 0x6c, 0x73, 0x22,
	0x43, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75,
	0x72, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x75, 0x72, 0x6c, 0x73, 0x22, 0x2e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75,
	0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x75, 0x72, 0x6c, 0x73, 0x22, 0x45, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x64, 0x65, 0x64, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x65,
	0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x28, 0x0a, 0x12, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x71, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x65, 0x6e, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x32, 0x47, 0x0a, 0x0b, 0x54, 0x65, 0x78, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x54, 0x65, 0x78, 0x74, 0x12, 0x13, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x74, 0x0a, 0x0a, 0x55, 0x72, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x38, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x13,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x55, 0x72, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x55, 0x72, 0x6c, 0x73, 0x12, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x22, 0x5a, 0x20, 0x73, 0x69, 0x67, 0x6d, 0x61,
	0x6f, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_apps_socialnetwork_proto_text_proto_rawDescOnce sync.Once
	file_apps_socialnetwork_proto_text_proto_rawDescData = file_apps_socialnetwork_proto_text_proto_rawDesc
)

func file_apps_socialnetwork_proto_text_proto_rawDescGZIP() []byte {
	file_apps_socialnetwork_proto_text_proto_rawDescOnce.Do(func() {
		file_apps_socialnetwork_proto_text_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_socialnetwork_proto_text_proto_rawDescData)
	})
	return file_apps_socialnetwork_proto_text_proto_rawDescData
}

var file_apps_socialnetwork_proto_text_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apps_socialnetwork_proto_text_proto_goTypes = []interface{}{
	(*ComposeUrlsRequest)(nil),  // 0: ComposeUrlsRequest
	(*ComposeUrlsResponse)(nil), // 1: ComposeUrlsResponse
	(*GetUrlsRequest)(nil),      // 2: GetUrlsRequest
	(*GetUrlsResponse)(nil),     // 3: GetUrlsResponse
	(*ProcessTextRequest)(nil),  // 4: ProcessTextRequest
	(*ProcessTextResponse)(nil), // 5: ProcessTextResponse
}
var file_apps_socialnetwork_proto_text_proto_depIdxs = []int32{
	4, // 0: TextService.ProcessText:input_type -> ProcessTextRequest
	0, // 1: UrlService.ComposeUrls:input_type -> ComposeUrlsRequest
	2, // 2: UrlService.GetUrls:input_type -> GetUrlsRequest
	5, // 3: TextService.ProcessText:output_type -> ProcessTextResponse
	1, // 4: UrlService.ComposeUrls:output_type -> ComposeUrlsResponse
	3, // 5: UrlService.GetUrls:output_type -> GetUrlsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_socialnetwork_proto_text_proto_init() }
func file_apps_socialnetwork_proto_text_proto_init() {
	if File_apps_socialnetwork_proto_text_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_socialnetwork_proto_text_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComposeUrlsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_socialnetwork_proto_text_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComposeUrlsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_socialnetwork_proto_text_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUrlsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_socialnetwork_proto_text_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUrlsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_socialnetwork_proto_text_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessTextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_socialnetwork_proto_text_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessTextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_socialnetwork_proto_text_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_apps_socialnetwork_proto_text_proto_goTypes,
		DependencyIndexes: file_apps_socialnetwork_proto_text_proto_depIdxs,
		MessageInfos:      file_apps_socialnetwork_proto_text_proto_msgTypes,
	}.Build()
	File_apps_socialnetwork_proto_text_proto = out.File
	file_apps_socialnetwork_proto_text_proto_rawDesc = nil
	file_apps_socialnetwork_proto_text_proto_goTypes = nil
	file_apps_socialnetwork_proto_text_proto_depIdxs = nil
}
