apiVersion: v1
kind: Pod
metadata:
  labels:
    service: netperf-clnt
  name: netperf-clnt
spec:
  containers:
    - name: netperf-clnt
      image: arielszekely/sigmaos-netperf:latest
      resources:
        requests:
          cpu: 2500m
      command: ["go"]
      args: ["test", "-v", "netperf", "--run", "TestClntDialTCP", "--srvaddr", "netperf-srv:8080", "--ntrial", "50"]
      ports:
        - containerPort: 8080
  restartPolicy: OnFailure
status: {}
