// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spin.proto

#include "spin.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR SpinReq::SpinReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.n_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SpinReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SpinReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SpinReqDefaultTypeInternal() {}
  union {
    SpinReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SpinReqDefaultTypeInternal _SpinReq_default_instance_;
PROTOBUF_CONSTEXPR SpinRep::SpinRep(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.n_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SpinRepDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SpinRepDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SpinRepDefaultTypeInternal() {}
  union {
    SpinRep _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SpinRepDefaultTypeInternal _SpinRep_default_instance_;
static ::_pb::Metadata file_level_metadata_spin_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_spin_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_spin_2eproto = nullptr;

const uint32_t TableStruct_spin_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::SpinReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::SpinReq, _impl_.n_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::SpinRep, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::SpinRep, _impl_.n_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::SpinReq)},
  { 7, -1, -1, sizeof(::SpinRep)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_SpinReq_default_instance_._instance,
  &::_SpinRep_default_instance_._instance,
};

const char descriptor_table_protodef_spin_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nspin.proto\"\024\n\007SpinReq\022\t\n\001n\030\001 \001(\003\"\024\n\007Sp"
  "inRep\022\t\n\001n\030\001 \001(\0032)\n\013SpinService\022\032\n\004Spin\022"
  "\010.SpinReq\032\010.SpinRepB\031Z\027sigmaos/apps/spin"
  "/protob\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_spin_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_spin_2eproto = {
    false, false, 134, descriptor_table_protodef_spin_2eproto,
    "spin.proto",
    &descriptor_table_spin_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_spin_2eproto::offsets,
    file_level_metadata_spin_2eproto, file_level_enum_descriptors_spin_2eproto,
    file_level_service_descriptors_spin_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_spin_2eproto_getter() {
  return &descriptor_table_spin_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_spin_2eproto(&descriptor_table_spin_2eproto);

// ===================================================================

class SpinReq::_Internal {
 public:
};

SpinReq::SpinReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:SpinReq)
}
SpinReq::SpinReq(const SpinReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SpinReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.n_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.n_ = from._impl_.n_;
  // @@protoc_insertion_point(copy_constructor:SpinReq)
}

inline void SpinReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.n_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SpinReq::~SpinReq() {
  // @@protoc_insertion_point(destructor:SpinReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SpinReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SpinReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SpinReq::Clear() {
// @@protoc_insertion_point(message_clear_start:SpinReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.n_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SpinReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 n = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.n_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SpinReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SpinReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 n = 1;
  if (this->_internal_n() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_n(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SpinReq)
  return target;
}

size_t SpinReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SpinReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 n = 1;
  if (this->_internal_n() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_n());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SpinReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SpinReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SpinReq::GetClassData() const { return &_class_data_; }


void SpinReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SpinReq*>(&to_msg);
  auto& from = static_cast<const SpinReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SpinReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_n() != 0) {
    _this->_internal_set_n(from._internal_n());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SpinReq::CopyFrom(const SpinReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SpinReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpinReq::IsInitialized() const {
  return true;
}

void SpinReq::InternalSwap(SpinReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.n_, other->_impl_.n_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SpinReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_spin_2eproto_getter, &descriptor_table_spin_2eproto_once,
      file_level_metadata_spin_2eproto[0]);
}

// ===================================================================

class SpinRep::_Internal {
 public:
};

SpinRep::SpinRep(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:SpinRep)
}
SpinRep::SpinRep(const SpinRep& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SpinRep* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.n_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.n_ = from._impl_.n_;
  // @@protoc_insertion_point(copy_constructor:SpinRep)
}

inline void SpinRep::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.n_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SpinRep::~SpinRep() {
  // @@protoc_insertion_point(destructor:SpinRep)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SpinRep::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SpinRep::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SpinRep::Clear() {
// @@protoc_insertion_point(message_clear_start:SpinRep)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.n_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SpinRep::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 n = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.n_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SpinRep::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SpinRep)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 n = 1;
  if (this->_internal_n() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_n(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SpinRep)
  return target;
}

size_t SpinRep::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SpinRep)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 n = 1;
  if (this->_internal_n() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_n());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SpinRep::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SpinRep::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SpinRep::GetClassData() const { return &_class_data_; }


void SpinRep::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SpinRep*>(&to_msg);
  auto& from = static_cast<const SpinRep&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SpinRep)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_n() != 0) {
    _this->_internal_set_n(from._internal_n());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SpinRep::CopyFrom(const SpinRep& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SpinRep)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpinRep::IsInitialized() const {
  return true;
}

void SpinRep::InternalSwap(SpinRep* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.n_, other->_impl_.n_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SpinRep::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_spin_2eproto_getter, &descriptor_table_spin_2eproto_once,
      file_level_metadata_spin_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::SpinReq*
Arena::CreateMaybeMessage< ::SpinReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SpinReq >(arena);
}
template<> PROTOBUF_NOINLINE ::SpinRep*
Arena::CreateMaybeMessage< ::SpinRep >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SpinRep >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
