// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cossim.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cossim_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cossim_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cossim_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cossim_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cossim_2eproto;
class CosSimRep;
struct CosSimRepDefaultTypeInternal;
extern CosSimRepDefaultTypeInternal _CosSimRep_default_instance_;
class CosSimReq;
struct CosSimReqDefaultTypeInternal;
extern CosSimReqDefaultTypeInternal _CosSimReq_default_instance_;
class VecRange;
struct VecRangeDefaultTypeInternal;
extern VecRangeDefaultTypeInternal _VecRange_default_instance_;
class Vector;
struct VectorDefaultTypeInternal;
extern VectorDefaultTypeInternal _Vector_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CosSimRep* Arena::CreateMaybeMessage<::CosSimRep>(Arena*);
template<> ::CosSimReq* Arena::CreateMaybeMessage<::CosSimReq>(Arena*);
template<> ::VecRange* Arena::CreateMaybeMessage<::VecRange>(Arena*);
template<> ::Vector* Arena::CreateMaybeMessage<::Vector>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Vector final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Vector) */ {
 public:
  inline Vector() : Vector(nullptr) {}
  ~Vector() override;
  explicit PROTOBUF_CONSTEXPR Vector(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vector(const Vector& from);
  Vector(Vector&& from) noexcept
    : Vector() {
    *this = ::std::move(from);
  }

  inline Vector& operator=(const Vector& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector& operator=(Vector&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vector& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vector* internal_default_instance() {
    return reinterpret_cast<const Vector*>(
               &_Vector_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Vector& a, Vector& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vector* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vector* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Vector>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vector& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Vector& from) {
    Vector::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Vector";
  }
  protected:
  explicit Vector(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValsFieldNumber = 1,
  };
  // repeated double vals = 1;
  int vals_size() const;
  private:
  int _internal_vals_size() const;
  public:
  void clear_vals();
  private:
  double _internal_vals(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_vals() const;
  void _internal_add_vals(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_vals();
  public:
  double vals(int index) const;
  void set_vals(int index, double value);
  void add_vals(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      vals() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_vals();

  // @@protoc_insertion_point(class_scope:Vector)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > vals_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cossim_2eproto;
};
// -------------------------------------------------------------------

class VecRange final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:VecRange) */ {
 public:
  inline VecRange() : VecRange(nullptr) {}
  ~VecRange() override;
  explicit PROTOBUF_CONSTEXPR VecRange(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VecRange(const VecRange& from);
  VecRange(VecRange&& from) noexcept
    : VecRange() {
    *this = ::std::move(from);
  }

  inline VecRange& operator=(const VecRange& from) {
    CopyFrom(from);
    return *this;
  }
  inline VecRange& operator=(VecRange&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VecRange& default_instance() {
    return *internal_default_instance();
  }
  static inline const VecRange* internal_default_instance() {
    return reinterpret_cast<const VecRange*>(
               &_VecRange_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(VecRange& a, VecRange& b) {
    a.Swap(&b);
  }
  inline void Swap(VecRange* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VecRange* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VecRange* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VecRange>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VecRange& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VecRange& from) {
    VecRange::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VecRange* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "VecRange";
  }
  protected:
  explicit VecRange(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStartIDFieldNumber = 1,
    kEndIDFieldNumber = 2,
  };
  // uint64 startID = 1;
  void clear_startid();
  uint64_t startid() const;
  void set_startid(uint64_t value);
  private:
  uint64_t _internal_startid() const;
  void _internal_set_startid(uint64_t value);
  public:

  // uint64 endID = 2;
  void clear_endid();
  uint64_t endid() const;
  void set_endid(uint64_t value);
  private:
  uint64_t _internal_endid() const;
  void _internal_set_endid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:VecRange)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t startid_;
    uint64_t endid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cossim_2eproto;
};
// -------------------------------------------------------------------

class CosSimReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CosSimReq) */ {
 public:
  inline CosSimReq() : CosSimReq(nullptr) {}
  ~CosSimReq() override;
  explicit PROTOBUF_CONSTEXPR CosSimReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CosSimReq(const CosSimReq& from);
  CosSimReq(CosSimReq&& from) noexcept
    : CosSimReq() {
    *this = ::std::move(from);
  }

  inline CosSimReq& operator=(const CosSimReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline CosSimReq& operator=(CosSimReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CosSimReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const CosSimReq* internal_default_instance() {
    return reinterpret_cast<const CosSimReq*>(
               &_CosSimReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CosSimReq& a, CosSimReq& b) {
    a.Swap(&b);
  }
  inline void Swap(CosSimReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CosSimReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CosSimReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CosSimReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CosSimReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CosSimReq& from) {
    CosSimReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CosSimReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CosSimReq";
  }
  protected:
  explicit CosSimReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVecRangesFieldNumber = 2,
    kInputVecFieldNumber = 1,
    kIDFieldNumber = 3,
  };
  // repeated .VecRange vecRanges = 2;
  int vecranges_size() const;
  private:
  int _internal_vecranges_size() const;
  public:
  void clear_vecranges();
  ::VecRange* mutable_vecranges(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::VecRange >*
      mutable_vecranges();
  private:
  const ::VecRange& _internal_vecranges(int index) const;
  ::VecRange* _internal_add_vecranges();
  public:
  const ::VecRange& vecranges(int index) const;
  ::VecRange* add_vecranges();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::VecRange >&
      vecranges() const;

  // .Vector inputVec = 1;
  bool has_inputvec() const;
  private:
  bool _internal_has_inputvec() const;
  public:
  void clear_inputvec();
  const ::Vector& inputvec() const;
  PROTOBUF_NODISCARD ::Vector* release_inputvec();
  ::Vector* mutable_inputvec();
  void set_allocated_inputvec(::Vector* inputvec);
  private:
  const ::Vector& _internal_inputvec() const;
  ::Vector* _internal_mutable_inputvec();
  public:
  void unsafe_arena_set_allocated_inputvec(
      ::Vector* inputvec);
  ::Vector* unsafe_arena_release_inputvec();

  // uint64 iD = 3;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:CosSimReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::VecRange > vecranges_;
    ::Vector* inputvec_;
    uint64_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cossim_2eproto;
};
// -------------------------------------------------------------------

class CosSimRep final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CosSimRep) */ {
 public:
  inline CosSimRep() : CosSimRep(nullptr) {}
  ~CosSimRep() override;
  explicit PROTOBUF_CONSTEXPR CosSimRep(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CosSimRep(const CosSimRep& from);
  CosSimRep(CosSimRep&& from) noexcept
    : CosSimRep() {
    *this = ::std::move(from);
  }

  inline CosSimRep& operator=(const CosSimRep& from) {
    CopyFrom(from);
    return *this;
  }
  inline CosSimRep& operator=(CosSimRep&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CosSimRep& default_instance() {
    return *internal_default_instance();
  }
  static inline const CosSimRep* internal_default_instance() {
    return reinterpret_cast<const CosSimRep*>(
               &_CosSimRep_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CosSimRep& a, CosSimRep& b) {
    a.Swap(&b);
  }
  inline void Swap(CosSimRep* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CosSimRep* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CosSimRep* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CosSimRep>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CosSimRep& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CosSimRep& from) {
    CosSimRep::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CosSimRep* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CosSimRep";
  }
  protected:
  explicit CosSimRep(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIDFieldNumber = 1,
    kValFieldNumber = 2,
  };
  // uint64 iD = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // double val = 2;
  void clear_val();
  double val() const;
  void set_val(double value);
  private:
  double _internal_val() const;
  void _internal_set_val(double value);
  public:

  // @@protoc_insertion_point(class_scope:CosSimRep)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t id_;
    double val_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cossim_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vector

// repeated double vals = 1;
inline int Vector::_internal_vals_size() const {
  return _impl_.vals_.size();
}
inline int Vector::vals_size() const {
  return _internal_vals_size();
}
inline void Vector::clear_vals() {
  _impl_.vals_.Clear();
}
inline double Vector::_internal_vals(int index) const {
  return _impl_.vals_.Get(index);
}
inline double Vector::vals(int index) const {
  // @@protoc_insertion_point(field_get:Vector.vals)
  return _internal_vals(index);
}
inline void Vector::set_vals(int index, double value) {
  _impl_.vals_.Set(index, value);
  // @@protoc_insertion_point(field_set:Vector.vals)
}
inline void Vector::_internal_add_vals(double value) {
  _impl_.vals_.Add(value);
}
inline void Vector::add_vals(double value) {
  _internal_add_vals(value);
  // @@protoc_insertion_point(field_add:Vector.vals)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
Vector::_internal_vals() const {
  return _impl_.vals_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
Vector::vals() const {
  // @@protoc_insertion_point(field_list:Vector.vals)
  return _internal_vals();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
Vector::_internal_mutable_vals() {
  return &_impl_.vals_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
Vector::mutable_vals() {
  // @@protoc_insertion_point(field_mutable_list:Vector.vals)
  return _internal_mutable_vals();
}

// -------------------------------------------------------------------

// VecRange

// uint64 startID = 1;
inline void VecRange::clear_startid() {
  _impl_.startid_ = uint64_t{0u};
}
inline uint64_t VecRange::_internal_startid() const {
  return _impl_.startid_;
}
inline uint64_t VecRange::startid() const {
  // @@protoc_insertion_point(field_get:VecRange.startID)
  return _internal_startid();
}
inline void VecRange::_internal_set_startid(uint64_t value) {
  
  _impl_.startid_ = value;
}
inline void VecRange::set_startid(uint64_t value) {
  _internal_set_startid(value);
  // @@protoc_insertion_point(field_set:VecRange.startID)
}

// uint64 endID = 2;
inline void VecRange::clear_endid() {
  _impl_.endid_ = uint64_t{0u};
}
inline uint64_t VecRange::_internal_endid() const {
  return _impl_.endid_;
}
inline uint64_t VecRange::endid() const {
  // @@protoc_insertion_point(field_get:VecRange.endID)
  return _internal_endid();
}
inline void VecRange::_internal_set_endid(uint64_t value) {
  
  _impl_.endid_ = value;
}
inline void VecRange::set_endid(uint64_t value) {
  _internal_set_endid(value);
  // @@protoc_insertion_point(field_set:VecRange.endID)
}

// -------------------------------------------------------------------

// CosSimReq

// .Vector inputVec = 1;
inline bool CosSimReq::_internal_has_inputvec() const {
  return this != internal_default_instance() && _impl_.inputvec_ != nullptr;
}
inline bool CosSimReq::has_inputvec() const {
  return _internal_has_inputvec();
}
inline void CosSimReq::clear_inputvec() {
  if (GetArenaForAllocation() == nullptr && _impl_.inputvec_ != nullptr) {
    delete _impl_.inputvec_;
  }
  _impl_.inputvec_ = nullptr;
}
inline const ::Vector& CosSimReq::_internal_inputvec() const {
  const ::Vector* p = _impl_.inputvec_;
  return p != nullptr ? *p : reinterpret_cast<const ::Vector&>(
      ::_Vector_default_instance_);
}
inline const ::Vector& CosSimReq::inputvec() const {
  // @@protoc_insertion_point(field_get:CosSimReq.inputVec)
  return _internal_inputvec();
}
inline void CosSimReq::unsafe_arena_set_allocated_inputvec(
    ::Vector* inputvec) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.inputvec_);
  }
  _impl_.inputvec_ = inputvec;
  if (inputvec) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CosSimReq.inputVec)
}
inline ::Vector* CosSimReq::release_inputvec() {
  
  ::Vector* temp = _impl_.inputvec_;
  _impl_.inputvec_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Vector* CosSimReq::unsafe_arena_release_inputvec() {
  // @@protoc_insertion_point(field_release:CosSimReq.inputVec)
  
  ::Vector* temp = _impl_.inputvec_;
  _impl_.inputvec_ = nullptr;
  return temp;
}
inline ::Vector* CosSimReq::_internal_mutable_inputvec() {
  
  if (_impl_.inputvec_ == nullptr) {
    auto* p = CreateMaybeMessage<::Vector>(GetArenaForAllocation());
    _impl_.inputvec_ = p;
  }
  return _impl_.inputvec_;
}
inline ::Vector* CosSimReq::mutable_inputvec() {
  ::Vector* _msg = _internal_mutable_inputvec();
  // @@protoc_insertion_point(field_mutable:CosSimReq.inputVec)
  return _msg;
}
inline void CosSimReq::set_allocated_inputvec(::Vector* inputvec) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.inputvec_;
  }
  if (inputvec) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(inputvec);
    if (message_arena != submessage_arena) {
      inputvec = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, inputvec, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.inputvec_ = inputvec;
  // @@protoc_insertion_point(field_set_allocated:CosSimReq.inputVec)
}

// repeated .VecRange vecRanges = 2;
inline int CosSimReq::_internal_vecranges_size() const {
  return _impl_.vecranges_.size();
}
inline int CosSimReq::vecranges_size() const {
  return _internal_vecranges_size();
}
inline void CosSimReq::clear_vecranges() {
  _impl_.vecranges_.Clear();
}
inline ::VecRange* CosSimReq::mutable_vecranges(int index) {
  // @@protoc_insertion_point(field_mutable:CosSimReq.vecRanges)
  return _impl_.vecranges_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::VecRange >*
CosSimReq::mutable_vecranges() {
  // @@protoc_insertion_point(field_mutable_list:CosSimReq.vecRanges)
  return &_impl_.vecranges_;
}
inline const ::VecRange& CosSimReq::_internal_vecranges(int index) const {
  return _impl_.vecranges_.Get(index);
}
inline const ::VecRange& CosSimReq::vecranges(int index) const {
  // @@protoc_insertion_point(field_get:CosSimReq.vecRanges)
  return _internal_vecranges(index);
}
inline ::VecRange* CosSimReq::_internal_add_vecranges() {
  return _impl_.vecranges_.Add();
}
inline ::VecRange* CosSimReq::add_vecranges() {
  ::VecRange* _add = _internal_add_vecranges();
  // @@protoc_insertion_point(field_add:CosSimReq.vecRanges)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::VecRange >&
CosSimReq::vecranges() const {
  // @@protoc_insertion_point(field_list:CosSimReq.vecRanges)
  return _impl_.vecranges_;
}

// uint64 iD = 3;
inline void CosSimReq::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t CosSimReq::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t CosSimReq::id() const {
  // @@protoc_insertion_point(field_get:CosSimReq.iD)
  return _internal_id();
}
inline void CosSimReq::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void CosSimReq::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:CosSimReq.iD)
}

// -------------------------------------------------------------------

// CosSimRep

// uint64 iD = 1;
inline void CosSimRep::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t CosSimRep::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t CosSimRep::id() const {
  // @@protoc_insertion_point(field_get:CosSimRep.iD)
  return _internal_id();
}
inline void CosSimRep::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void CosSimRep::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:CosSimRep.iD)
}

// double val = 2;
inline void CosSimRep::clear_val() {
  _impl_.val_ = 0;
}
inline double CosSimRep::_internal_val() const {
  return _impl_.val_;
}
inline double CosSimRep::val() const {
  // @@protoc_insertion_point(field_get:CosSimRep.val)
  return _internal_val();
}
inline void CosSimRep::_internal_set_val(double value) {
  
  _impl_.val_ = value;
}
inline void CosSimRep::set_val(double value) {
  _internal_set_val(value);
  // @@protoc_insertion_point(field_set:CosSimRep.val)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cossim_2eproto
