// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: schedd/proto/schedd.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	proc "sigmaos/proc"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpawnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Realm     string          `protobuf:"bytes,1,opt,name=realm,proto3" json:"realm,omitempty"`
	ProcProto *proc.ProcProto `protobuf:"bytes,2,opt,name=procProto,proto3" json:"procProto,omitempty"`
}

func (x *SpawnRequest) Reset() {
	*x = SpawnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedd_proto_schedd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnRequest) ProtoMessage() {}

func (x *SpawnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedd_proto_schedd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnRequest.ProtoReflect.Descriptor instead.
func (*SpawnRequest) Descriptor() ([]byte, []int) {
	return file_schedd_proto_schedd_proto_rawDescGZIP(), []int{0}
}

func (x *SpawnRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *SpawnRequest) GetProcProto() *proc.ProcProto {
	if x != nil {
		return x.ProcProto
	}
	return nil
}

type SpawnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpawnResponse) Reset() {
	*x = SpawnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedd_proto_schedd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnResponse) ProtoMessage() {}

func (x *SpawnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schedd_proto_schedd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnResponse.ProtoReflect.Descriptor instead.
func (*SpawnResponse) Descriptor() ([]byte, []int) {
	return file_schedd_proto_schedd_proto_rawDescGZIP(), []int{1}
}

type StealProcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScheddIp string `protobuf:"bytes,1,opt,name=scheddIp,proto3" json:"scheddIp,omitempty"`
	Realm    string `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	PidStr   string `protobuf:"bytes,3,opt,name=pidStr,proto3" json:"pidStr,omitempty"`
}

func (x *StealProcRequest) Reset() {
	*x = StealProcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedd_proto_schedd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StealProcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StealProcRequest) ProtoMessage() {}

func (x *StealProcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedd_proto_schedd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StealProcRequest.ProtoReflect.Descriptor instead.
func (*StealProcRequest) Descriptor() ([]byte, []int) {
	return file_schedd_proto_schedd_proto_rawDescGZIP(), []int{2}
}

func (x *StealProcRequest) GetScheddIp() string {
	if x != nil {
		return x.ScheddIp
	}
	return ""
}

func (x *StealProcRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *StealProcRequest) GetPidStr() string {
	if x != nil {
		return x.PidStr
	}
	return ""
}

type StealProcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK bool `protobuf:"varint,1,opt,name=oK,proto3" json:"oK,omitempty"`
}

func (x *StealProcResponse) Reset() {
	*x = StealProcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedd_proto_schedd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StealProcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StealProcResponse) ProtoMessage() {}

func (x *StealProcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schedd_proto_schedd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StealProcResponse.ProtoReflect.Descriptor instead.
func (*StealProcResponse) Descriptor() ([]byte, []int) {
	return file_schedd_proto_schedd_proto_rawDescGZIP(), []int{3}
}

func (x *StealProcResponse) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

type GetCPUSharesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCPUSharesRequest) Reset() {
	*x = GetCPUSharesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedd_proto_schedd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCPUSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCPUSharesRequest) ProtoMessage() {}

func (x *GetCPUSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedd_proto_schedd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCPUSharesRequest.ProtoReflect.Descriptor instead.
func (*GetCPUSharesRequest) Descriptor() ([]byte, []int) {
	return file_schedd_proto_schedd_proto_rawDescGZIP(), []int{4}
}

type GetCPUSharesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shares map[string]int64 `protobuf:"bytes,1,rep,name=shares,proto3" json:"shares,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *GetCPUSharesResponse) Reset() {
	*x = GetCPUSharesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedd_proto_schedd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCPUSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCPUSharesResponse) ProtoMessage() {}

func (x *GetCPUSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schedd_proto_schedd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCPUSharesResponse.ProtoReflect.Descriptor instead.
func (*GetCPUSharesResponse) Descriptor() ([]byte, []int) {
	return file_schedd_proto_schedd_proto_rawDescGZIP(), []int{5}
}

func (x *GetCPUSharesResponse) GetShares() map[string]int64 {
	if x != nil {
		return x.Shares
	}
	return nil
}

type GetCPUUtilRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealmStr string `protobuf:"bytes,1,opt,name=realmStr,proto3" json:"realmStr,omitempty"`
}

func (x *GetCPUUtilRequest) Reset() {
	*x = GetCPUUtilRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedd_proto_schedd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCPUUtilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCPUUtilRequest) ProtoMessage() {}

func (x *GetCPUUtilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedd_proto_schedd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCPUUtilRequest.ProtoReflect.Descriptor instead.
func (*GetCPUUtilRequest) Descriptor() ([]byte, []int) {
	return file_schedd_proto_schedd_proto_rawDescGZIP(), []int{6}
}

func (x *GetCPUUtilRequest) GetRealmStr() string {
	if x != nil {
		return x.RealmStr
	}
	return ""
}

type GetCPUUtilResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Util float64 `protobuf:"fixed64,1,opt,name=util,proto3" json:"util,omitempty"`
}

func (x *GetCPUUtilResponse) Reset() {
	*x = GetCPUUtilResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schedd_proto_schedd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCPUUtilResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCPUUtilResponse) ProtoMessage() {}

func (x *GetCPUUtilResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schedd_proto_schedd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCPUUtilResponse.ProtoReflect.Descriptor instead.
func (*GetCPUUtilResponse) Descriptor() ([]byte, []int) {
	return file_schedd_proto_schedd_proto_rawDescGZIP(), []int{7}
}

func (x *GetCPUUtilResponse) GetUtil() float64 {
	if x != nil {
		return x.Util
	}
	return 0
}

var File_schedd_proto_schedd_proto protoreflect.FileDescriptor

var file_schedd_proto_schedd_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x63, 0x68, 0x65, 0x64, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x70, 0x72, 0x6f,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x0c,
	0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x65, 0x61, 0x6c, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x61,
	0x6c, 0x6d, 0x12, 0x28, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0f, 0x0a, 0x0d,
	0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5c, 0x0a,
	0x10, 0x53, 0x74, 0x65, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x63, 0x68, 0x65, 0x64, 0x64, 0x49, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x63, 0x68, 0x65, 0x64, 0x64, 0x49, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65,
	0x61, 0x6c, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x69, 0x64, 0x53, 0x74, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x69, 0x64, 0x53, 0x74, 0x72, 0x22, 0x23, 0x0a, 0x11, 0x53,
	0x74, 0x65, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x4b,
	0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x50, 0x55, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8c, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43,
	0x50, 0x55, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x39, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x50, 0x55, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2f, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x50, 0x55,
	0x55, 0x74, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x61, 0x6c, 0x6d, 0x53, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x61, 0x6c, 0x6d, 0x53, 0x74, 0x72, 0x22, 0x28, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x50,
	0x55, 0x55, 0x74, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x74, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x75, 0x74, 0x69,
	0x6c, 0x32, 0xa1, 0x01, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65, 0x64, 0x64, 0x12, 0x26, 0x0a, 0x05,
	0x53, 0x70, 0x61, 0x77, 0x6e, 0x12, 0x0d, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x53, 0x74, 0x65, 0x61, 0x6c, 0x50, 0x72, 0x6f,
	0x63, 0x12, 0x11, 0x2e, 0x53, 0x74, 0x65, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x53, 0x74, 0x65, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x63,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43,
	0x50, 0x55, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x50,
	0x55, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x50, 0x55, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x6f, 0x73,
	0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schedd_proto_schedd_proto_rawDescOnce sync.Once
	file_schedd_proto_schedd_proto_rawDescData = file_schedd_proto_schedd_proto_rawDesc
)

func file_schedd_proto_schedd_proto_rawDescGZIP() []byte {
	file_schedd_proto_schedd_proto_rawDescOnce.Do(func() {
		file_schedd_proto_schedd_proto_rawDescData = protoimpl.X.CompressGZIP(file_schedd_proto_schedd_proto_rawDescData)
	})
	return file_schedd_proto_schedd_proto_rawDescData
}

var file_schedd_proto_schedd_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_schedd_proto_schedd_proto_goTypes = []interface{}{
	(*SpawnRequest)(nil),         // 0: SpawnRequest
	(*SpawnResponse)(nil),        // 1: SpawnResponse
	(*StealProcRequest)(nil),     // 2: StealProcRequest
	(*StealProcResponse)(nil),    // 3: StealProcResponse
	(*GetCPUSharesRequest)(nil),  // 4: GetCPUSharesRequest
	(*GetCPUSharesResponse)(nil), // 5: GetCPUSharesResponse
	(*GetCPUUtilRequest)(nil),    // 6: GetCPUUtilRequest
	(*GetCPUUtilResponse)(nil),   // 7: GetCPUUtilResponse
	nil,                          // 8: GetCPUSharesResponse.SharesEntry
	(*proc.ProcProto)(nil),       // 9: ProcProto
}
var file_schedd_proto_schedd_proto_depIdxs = []int32{
	9, // 0: SpawnRequest.procProto:type_name -> ProcProto
	8, // 1: GetCPUSharesResponse.shares:type_name -> GetCPUSharesResponse.SharesEntry
	0, // 2: Schedd.Spawn:input_type -> SpawnRequest
	2, // 3: Schedd.StealProc:input_type -> StealProcRequest
	4, // 4: Schedd.GetCPUShares:input_type -> GetCPUSharesRequest
	1, // 5: Schedd.Spawn:output_type -> SpawnResponse
	3, // 6: Schedd.StealProc:output_type -> StealProcResponse
	5, // 7: Schedd.GetCPUShares:output_type -> GetCPUSharesResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_schedd_proto_schedd_proto_init() }
func file_schedd_proto_schedd_proto_init() {
	if File_schedd_proto_schedd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schedd_proto_schedd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schedd_proto_schedd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schedd_proto_schedd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StealProcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schedd_proto_schedd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StealProcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schedd_proto_schedd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCPUSharesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schedd_proto_schedd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCPUSharesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schedd_proto_schedd_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCPUUtilRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schedd_proto_schedd_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCPUUtilResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schedd_proto_schedd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schedd_proto_schedd_proto_goTypes,
		DependencyIndexes: file_schedd_proto_schedd_proto_depIdxs,
		MessageInfos:      file_schedd_proto_schedd_proto_msgTypes,
	}.Build()
	File_schedd_proto_schedd_proto = out.File
	file_schedd_proto_schedd_proto_rawDesc = nil
	file_schedd_proto_schedd_proto_goTypes = nil
	file_schedd_proto_schedd_proto_depIdxs = nil
}
